### PR TITLE
fix: fix compiler nodeResolve

### LINKED ISSUE #3: Error [RollupError]: Could not resolve "./events/playerConnect" from "src/core/server/index.ts"
Hello,
When importing modules into the main Rollup file, Rollup is unable to resolve the given import, resulting in the error: "Error [RollupError]: Could not resolve "./events/playerConnect" from "src/core/server/index.ts"."

### PR DESCRIPTION
**Pull request by SarotaM**
Closes #3

### CODE REVIEW

File: scripts/compiler.ts [hunk 1]
```diff
@@ -34,7 +34,12 @@ const buildTargetResource = async (name: string) => {
     ['client', 'server'].forEach(async (dir) => {
         const bundle = await rollup({
             input: `./src/${name}/${dir}/index.ts`,
-            plugins: [nodeResolve(), commonjs(), terser(), swcPlugin({ swc: swcOptions })],
+            plugins: [
+                nodeResolve({ extensions: ['.js', '.jsx', '.ts', '.tsx'] }),
```
Comment (carlos-menezes) [inline scripts/compiler.ts]: We only want to resolve `ts` files.

**Review by carlos-menezes — CHANGES_REQUESTED** [review]
Thank you for submitting the PR!

File: scripts/compiler.ts (hunk 1 above)
Comment (SarotaM) [reply scripts/compiler.ts]: I'll fix it on Monday 😊

**Review by carlos-menezes — APPROVED** [review]
